services:
  api:
    image: todo-api:latest
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=host.docker.internal
      - DB_PORT=1433
      - DB_NAME=Todos
      - DB_TRUSTED_CONNECTION=no
      - DB_USER=sa
      - DB_PASSWORD=YourActualSaPassword
      - SERVER_PORT=8080
    extra_hosts:
      - "host.docker.internal:host-gateway"